export type LangCode = 'en' | 'id' | 'my' | 'th' | 'ph' | 'vn';

export const ASEAN_LANGUAGES = [
  { code: 'id' as LangCode, name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'my' as LangCode, name: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'en' as LangCode, name: 'English (SG)', flag: '🇸🇬' },
  { code: 'th' as LangCode, name: 'ไทย', flag: '🇹🇭' },
  { code: 'ph' as LangCode, name: 'Filipino', flag: '🇵🇭' },
  { code: 'vn' as LangCode, name: 'Tiếng Việt', flag: '🇻🇳' },
];

export const translations = {
  en: {
    title: "TRACIA Academic Intelligence",
    studentPortal: "STUDENT PORTAL",
    adminPortal: "ACADEMIC INTELLIGENCE PORTAL (LECTURER / ADMIN)",
    successPotential: "Success Potential",
    gpaStatus: "GPA Status",
    financials: "Financials",
    coursePasses: "Course Passes",
    creditVelocity: "Credit Velocity",
    recoveryRoadmap: "Recovery Roadmap",
    opportunityHub: "Opportunity Hub",
    quests: "Quests & Gamification",
    messages: "Messages & AI Mentor",
    academics: "Academic Documents",
    logout: "Logout",
    riskLevel: "Risk Level",
    dropoutProb: "Dropout Probability",
    weeklyProgress: "Weekly Progress",
    searchPlaceholder: "Search opportunities...",
    careerGoal: "Career Goal Progress Tracker",
    advisorInterventions: "Lecturer Intervention & Nudges",
    priorityActions: "Priority Study Actions",
    growthInsights: "AI Growth Insights",
    watchlist: "Student Watchlist",
    selectStudent: "Select a Student",
    triageMatrix: "Interactive Triage Matrix",
    burnoutRadar: "Burnout & Stress Distribution Radar",
    interventionLog: "Active Interventions History",
    classReports: "Class Reports",
    institutionalInsights: "Institutional Insights",
    alerts: "Active System Alerts",
    userManagement: "Register Campus Account",
    dataIntegration: "Academic API Data Synchronization Monitor",
    aiModel: "XGBoost Model Diagnostics",
    security: "Access Control & Security Settings",
    languageSetting: "Language Setting",
    studentAnalysis: "Student Analysis"
  },
  id: {
    title: "Inteligensia Akademik TRACIA",
    studentPortal: "PORTAL MAHASISWA",
    adminPortal: "PORTAL INTELIGENSIA AKADEMIK (DOSEN / ADMIN)",
    successPotential: "Potensi Keberhasilan",
    gpaStatus: "Status IPK",
    financials: "Keuangan",
    coursePasses: "Kelulusan Kuliah",
    creditVelocity: "Kecepatan Kredit",
    recoveryRoadmap: "Rencana Pemulihan",
    opportunityHub: "Pusat Peluang",
    quests: "Misi & Gamifikasi",
    messages: "Pesan & Mentor AI",
    academics: "Dokumen Akademik",
    logout: "Keluar",
    riskLevel: "Tingkat Risiko",
    dropoutProb: "Probabilitas Dropout",
    weeklyProgress: "Kemajuan Mingguan",
    searchPlaceholder: "Cari peluang...",
    careerGoal: "Pelacak Kemajuan Tujuan Karir",
    advisorInterventions: "Intervensi & Nasihat Dosen",
    priorityActions: "Tindakan Prioritas Studi",
    growthInsights: "Wawasan Pertumbuhan AI",
    watchlist: "Daftar Pantau Mahasiswa",
    selectStudent: "Pilih Mahasiswa",
    triageMatrix: "Matriks Triase Interaktif",
    burnoutRadar: "Radar Burnout & Distribusi Stres",
    interventionLog: "Riwayat Intervensi Aktif",
    classReports: "Laporan Perkembangan Kelas",
    institutionalInsights: "Wawasan Institusi",
    alerts: "Peringatan Sistem Aktif",
    userManagement: "Daftar Akun Kampus",
    dataIntegration: "Monitor Sinkronisasi Data API Akademik",
    aiModel: "Diagnostik Model AI XGBoost",
    security: "Pengaturan Kontrol Akses & Keamanan",
    languageSetting: "Pengaturan Bahasa",
    studentAnalysis: "Analisis Mahasiswa"
  },
  my: {
    title: "Kecerdasan Akademik TRACIA",
    studentPortal: "PORTAL PELAJAR",
    adminPortal: "PORTAL KECERDASAN AKADEMIK (PENSYARAH / ADMIN)",
    successPotential: "Potensi Kejayaan",
    gpaStatus: "Status PNGK",
    financials: "Kewangan",
    coursePasses: "Kelulusan Kursus",
    creditVelocity: "Kelajuan Kredit",
    recoveryRoadmap: "Laluan Pemulihan",
    opportunityHub: "Pusat Peluang",
    quests: "Misi & Gamifikasi",
    messages: "Mesej & Mentor AI",
    academics: "Dokumen Akademik",
    logout: "Log Keluar",
    riskLevel: "Tahap Risiko",
    dropoutProb: "Kebarangkalian Dropout",
    weeklyProgress: "Kemajuan Mingguan",
    searchPlaceholder: "Cari peluang...",
    careerGoal: "Penjejak Kemajuan Matlamat Kerjaya",
    advisorInterventions: "Intervensi & Nasihat Pensyarah",
    priorityActions: "Tindakan Utama Pengajian",
    growthInsights: "Wawasan Pertumbuhan AI",
    watchlist: "Senarai Pantau Pelajar",
    selectStudent: "Pilih Pelajar",
    triageMatrix: "Matriks Triase Interaktif",
    burnoutRadar: "Radar Burnout & Taburan Stres",
    interventionLog: "Sejarah Intervensi Aktif",
    classReports: "Laporan Kemajuan Kelas",
    institutionalInsights: "Wawasan Institusi",
    alerts: "Amaran Sistem Aktif",
    userManagement: "Daftar Akaun Kampus",
    dataIntegration: "Monitor Sinkronisasi Data API Akademik",
    aiModel: "Diagnostik Model AI XGBoost",
    security: "Kawalan Akses & Keselamatan",
    languageSetting: "Tetapan Bahasa",
    studentAnalysis: "Analisis Pelajar"
  },
  th: {
    title: "TRACIA ระบบปัญญาประดิษฐ์เพื่อการศึกษา",
    studentPortal: "พอร์ทัลนักศึกษา",
    adminPortal: "พอร์ทัลปัญญาประดิษฐ์ทางวิชาการ (อาจารย์ / ผู้ดูแลระบบ)",
    successPotential: "ศักยภาพความสำเร็จ",
    gpaStatus: "สถานะเกรดเฉลี่ย",
    financials: "การเงิน",
    coursePasses: "การผ่านรายวิชา",
    creditVelocity: "ความเร็วหน่วยกิต",
    recoveryRoadmap: "แผนฟื้นฟูการเรียน",
    opportunityHub: "ศูนย์โอกาส",
    quests: "ภารกิจและเกมมิฟิเคชัน",
    messages: "ข้อความและที่ปรึกษา AI",
    academics: "เอกสารวิชาการ",
    logout: "ออกจากระบบ",
    riskLevel: "ระดับความเสี่ยง",
    dropoutProb: "โอกาสการลาออก",
    weeklyProgress: "ความก้าวหน้ารายสัปดาห์",
    searchPlaceholder: "ค้นหาโอกาส...",
    careerGoal: "เครื่องมือติดตามเป้าหมายอาชีพ",
    advisorInterventions: "การแจ้งเตือนและการแทรกแซงจากอาจารย์",
    priorityActions: "การดำเนินการศึกษาที่มีลำดับความสำคัญ",
    growthInsights: "ข้อมูลเชิงลึกการเติบโตโดย AI",
    watchlist: "รายชื่อนักศึกษาที่ต้องเฝ้าระวัง",
    selectStudent: "เลือกนักศึกษา",
    triageMatrix: "เมทริกซ์การคัดกรองแบบโต้ตอบ",
    burnoutRadar: "เรดาร์ตรวจจับภาวะหมดไฟและการกระจายความเครียด",
    interventionLog: "ประวัติการแทรกแซงที่ใช้งานอยู่",
    classReports: "รายงานความก้าวหน้าของชั้นเรียน",
    institutionalInsights: "ข้อมูลเชิงลึกระดับสถาบัน",
    alerts: "การแจ้งเตือนระบบที่ใช้งานอยู่",
    userManagement: "ลงทะเบียนบัญชีมหาวิทยาลัย",
    dataIntegration: "การตรวจสอบการซิงโครไนซ์ข้อมูล API วิชาการ",
    aiModel: "การวินิจฉัยรุ่น AI XGBoost",
    security: "การตั้งค่าการควบคุมการเข้าถึงและความปลอดภัย",
    languageSetting: "ตั้งค่าภาษา",
    studentAnalysis: "การวิเคราะห์นักศึกษา"
  },
  ph: {
    title: "TRACIA Akademikong Katalinuhan",
    studentPortal: "PORTAL NG ESTUDYANTE",
    adminPortal: "AKADEMIKONG KATALINUHAN PORTAL (LECTURER / ADMIN)",
    successPotential: "Potensyal ng Tagumpay",
    gpaStatus: "Katayuan ng GPA",
    financials: "Pinansyal",
    coursePasses: "Pasa sa Kurso",
    creditVelocity: "Bilis ng Credit",
    recoveryRoadmap: "Roadmap ng Pagbawi",
    opportunityHub: "Hub ng Oportunidad",
    quests: "Mga Quest at Gamification",
    messages: "Mga Mensahe at AI Mentor",
    academics: "Mga Dokumentong Akademiko",
    logout: "Mag-logout",
    riskLevel: "Antas ng Panganib",
    dropoutProb: "Probabilidad ng Dropout",
    weeklyProgress: "Lingguhang Pag-unlad",
    searchPlaceholder: "Maghanap ng mga pagkakataon...",
    careerGoal: "Tagasubaybay ng Layunin sa Karera",
    advisorInterventions: "Interbensyon at Nudges ng Lektor",
    priorityActions: "Mga Prayoridad na Aksyon sa Pag-aaral",
    growthInsights: "Mga Insight sa Paglago ng AI",
    watchlist: "Watchlist ng Estudyante",
    selectStudent: "Pumili ng Estudyante",
    triageMatrix: "Interactive Triage Matrix",
    burnoutRadar: "Burnout at Stress Distribution Radar",
    interventionLog: "Kasaysayan ng Aktibong Interbensyon",
    classReports: "Mga Ulat sa Klase",
    institutionalInsights: "Mga Insight sa Institusyon",
    alerts: "Aktibong System Alerts",
    userManagement: "Magrehistro ng Account",
    dataIntegration: "Monitor ng Sinkronisasyon ng Data ng Akademikong API",
    aiModel: "Mga Diagnostic ng Modelong AI XGBoost",
    security: "Kontrol sa Akses at Mga Setting ng Seguridad",
    languageSetting: "Mga Setting ng Wika",
    studentAnalysis: "Pagsusuri ng Estudyante"
  },
  vn: {
    title: "Trí tuệ học thuật TRACIA",
    studentPortal: "CỔNG THÔNG TIN SINH VIÊN",
    adminPortal: "CỔNG THÔNG TIN TRÍ TUỆ HỌC THUẬT (GIẢNG VIÊN / ADMIN)",
    successPotential: "Tiềm năng Thành công",
    gpaStatus: "Trạng thái GPA",
    financials: "Tài chính",
    coursePasses: "Hoàn thành Khóa học",
    creditVelocity: "Tốc độ Tín chỉ",
    recoveryRoadmap: "Lộ trình Phục hồi",
    opportunityHub: "Trung tâm Cơ hội",
    quests: "Nhiệm vụ & Gamification",
    messages: "Tin nhắn & Mentor AI",
    academics: "Tài liệu Học thuật",
    logout: "Đăng xuất",
    riskLevel: "Mức độ Rủi ro",
    dropoutProb: "Xác suất Thôi học",
    weeklyProgress: "Tiến độ Hàng tuần",
    searchPlaceholder: "Tìm kiếm cơ hội...",
    careerGoal: "Trình theo dõi mục tiêu nghề nghiệp",
    advisorInterventions: "Can thiệp & Nhắc nhở của Giảng viên",
    priorityActions: "Hành động Ưu tiên Học tập",
    growthInsights: "Thông tin Tăng trưởng AI",
    watchlist: "Danh sách Theo dõi Sinh viên",
    selectStudent: "Chọn một Sinh viên",
    triageMatrix: "Ma trận Triage tương tác",
    burnoutRadar: "Radar Burnout & Phân phối Căng thẳng",
    interventionLog: "Lịch sử Can thiệp Chủ động",
    classReports: "Báo cáo Tiến độ Lớp học",
    institutionalInsights: "Thông tin chi tiết về tổ chức",
    alerts: "Cảnh báo hệ thống đang hoạt động",
    userManagement: "Đăng ký tài khoản",
    dataIntegration: "Giám sát đồng bộ hóa dữ liệu API học thuật",
    aiModel: "Chẩn đoán mô hình AI XGBoost",
    security: "Cài đặt Kiểm soát Truy cập & Bảo mật",
    languageSetting: "Cài đặt ngôn ngữ",
    studentAnalysis: "Phân tích Sinh viên"
  }
};

export const getTranslation = (lang: LangCode) => {
  return translations[lang] || translations.en;
};
